### ISSUE TITLE
fcc - weather todo

### ISSUE THREAD

**Issue by krisztin** [krisztin/projects#13]
- [x] need to change .html to the updated version

- [x] geo location error handling
- [x]   pressing F button keep multiplying the temperature value
- [x]   de-jQuery'fied
- [x]   adding loading functionality
- [x]   fixing converting, mainly so that converting back to Celsius did not mean making another GET request and complete reload
